spring:
  application:
    name: people-service
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8080

clientsConfiguration:
  schoolService:
    host: http://localhost:8000
